//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class chatmessage
    {
        public long Id { get; set; }
        public long Sender_Id { get; set; }
        public long Chatroom_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
    
        public virtual chatroom chatroom { get; set; }
        public virtual employee employee { get; set; }

        //public employee EmployeeName
        //{
        //    get
        //    {
        //        if(this.employee == null)
        //        {
        //            return null;
        //        }
        //        return employee;
        //    }
        //}
    }

}
