//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        public long Id { get; set; }
        public long Employee_Id { get; set; }
        public long Chatroom_Id { get; set; }
    
        public virtual chatroom chatroom { get; set; }
        public virtual employee employee { get; set; }
    }
}
